spring.application.name=gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# JWT (debe coincidir con el config-server)
jwt.secret=${JWT_SECRET:clave-super-secreta-de-al-menos-32-caracteres-para-hs256}
jwt.issuer=${JWT_ISSUER:digital-money}

# Rutas del Gateway
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
