spring.application.name=gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# JWT (debe coincidir con el config-server)
jwt.secret=${JWT_SECRET:digitalMoneyHouseSecretKeyForJWT2024MustBeLongEnoughForHS256Algorithm}
jwt.issuer=${JWT_ISSUER:digital-money-house-user-service}

# Rutas del Gateway
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=lb://account-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/**

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
